name: firstly
description: "A new Flutter project."
# La ligne suivante empêche le package d'être accidentellement publié sur pub.dev en utilisant `flutter pub publish`.
# Cela est préférable pour les packages privés.
publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier sur pub.dev

# La section suivante définit la version et le numéro de build de votre application.
# Un numéro de version est constitué de trois nombres séparés par des points, comme 1.2.43,
# suivi éventuellement d'un numéro de build séparé par un +.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Mise à jour de la version minimale du SDK Flutter

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^25.1.41
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ajoutez ici vos assets, fonts, etc., si nécessaire
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
