// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0G-PAtaFoNCYzJg69x-8bQp0QrQ6gLKQ',
    appId: '1:915363184209:web:d52a52b9160a6f20a14270',
    messagingSenderId: '915363184209',
    projectId: 'temp-d04a4',
    authDomain: 'temp-d04a4.firebaseapp.com',
    storageBucket: 'temp-d04a4.appspot.com',
    measurementId: 'G-BEN9XRE0PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVXCzy_t-xAYMiLkvbJWvSbdyZTXcJfM',
    appId: '1:915363184209:android:1766b412ec05b8eca14270',
    messagingSenderId: '915363184209',
    projectId: 'temp-d04a4',
    storageBucket: 'temp-d04a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6dL0l5nJ8j0IXYU34OdURiibJyR8po4',
    appId: '1:915363184209:ios:0966a1a4251664c7a14270',
    messagingSenderId: '915363184209',
    projectId: 'temp-d04a4',
    storageBucket: 'temp-d04a4.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK6dL0l5nJ8j0IXYU34OdURiibJyR8po4',
    appId: '1:915363184209:ios:0966a1a4251664c7a14270',
    messagingSenderId: '915363184209',
    projectId: 'temp-d04a4',
    storageBucket: 'temp-d04a4.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0G-PAtaFoNCYzJg69x-8bQp0QrQ6gLKQ',
    appId: '1:915363184209:web:8933808ede26080fa14270',
    messagingSenderId: '915363184209',
    projectId: 'temp-d04a4',
    authDomain: 'temp-d04a4.firebaseapp.com',
    storageBucket: 'temp-d04a4.appspot.com',
    measurementId: 'G-0XN3PJ6XWQ',
  );
}
